// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'compose-header': string;
  'dddcc': string;
  'header': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
