// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'header-use-var': string;
  'header-with-componse': string;
  'header-with-import': string;
  'nest': string;
  's-header': string;
  'test-new': string;
  'v-primary': string;
}
export const cssExports: CssExports;
export default cssExports;
