// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header-use-less': string;
  'nest': string;
}
declare var cssExports: CssExports;
export = cssExports;
